import mongoose from 'mongoose';
import dotenv from 'dotenv';
import { User } from '../models/User';
import { Category } from '../models/Category';
import { Brand } from '../models/Brand';
import { Product } from '../models/Product';
import { Review } from '../models/Review';
import { Coupon } from '../models/Coupon';
import { Order } from '../models/Order';
import { connectDB, disconnectDB } from '../config/db';

dotenv.config();

const categoriesData = [
  {
    name: 'Sneakers',
    slug: 'sneakers',
    description: 'Iconic street silhouettes crafted for elevated everyday expression.',
    image: 'https://images.unsplash.com/photo-1552346154-21d32810aba3?w=1000&auto=format&fit=crop&q=85',
    order: 1,
  },
  {
    name: 'Running',
    slug: 'running',
    description: 'Precision-engineered propulsion and responsive energy return.',
    image: '/products/showcase/road_marathon.jpg',
    order: 2,
  },
  {
    name: 'Casual',
    slug: 'casual',
    description: 'Effortless luxury and breathable minimalism for any setting.',
    image: '/products/aeropulse/swiftstride_profile.jpg',
    order: 3,
  },
  {
    name: 'Sports',
    slug: 'sports',
    description: 'Elite training footwear delivering multi-directional stability.',
    image: 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=1000&auto=format&fit=crop&q=85',
    order: 4,
  },
  {
    name: 'Lifestyle',
    slug: 'lifestyle',
    description: 'Architectural footwear sculpted with artisan Italian leathers.',
    image: 'https://images.unsplash.com/photo-1533867617858-e7b97e060509?w=1000&auto=format&fit=crop&q=85',
    order: 5,
  },
  {
    name: 'Basketball',
    slug: 'basketball',
    description: 'Explosive vertical cushion and lockdown ankle support.',
    image: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=1000&auto=format&fit=crop&q=85',
    order: 6,
  },
];

const brandsData = [
  {
    name: 'SOLEVA Core',
    slug: 'soleva-core',
    description: 'Signature architectural footwear built with proprietary AeroCell cushioning.',
  },
  {
    name: 'AeroPulse',
    slug: 'aeropulse',
    description: 'Ultra-lightweight marathon and speed-training innovations.',
  },
  {
    name: 'Veloce',
    slug: 'veloce',
    description: 'Italian-designed luxury sneakers marrying heritage and modern edge.',
  },
  {
    name: 'Stratos',
    slug: 'stratos',
    description: 'Technical all-terrain and trail-ready hybrid silhouettes.',
  },
  {
    name: 'ApexLab',
    slug: 'apexlab',
    description: 'Futuristic concept footwear utilizing carbon-fiber kinetic plates.',
  },
];

const productsData = [
  {
    name: 'AeroCell Kinetic Runner',
    slug: 'aerocell-kinetic-runner',
    brand: 'SOLEVA Core',
    category: 'Running',
    gender: 'unisex',
    description: 'Engineered for relentless forward momentum. The AeroCell Kinetic Runner features our proprietary supercritical foam midsole, providing 84% energy return with featherlight 230g construction. The engineered mono-mesh upper guarantees targeted breathability across high-heat zones, while the carbon-infused torsion shank ensures fluid transition from heel-strike to toe-off.',
    shortDescription: 'Ultra-lightweight supercritical foam runner with carbon-infused torsion shank.',
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1512374382149-233c42b6a83b?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1512374382149-233c42b6a83b?w=1200&auto=format&fit=crop&q=85',
    ],
    price: 14995,
    compareAtPrice: 17995,
    colors: [
      {
        name: 'Crimson Ember',
        hex: '#E63946',
        image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=1200&auto=format&fit=crop&q=85',
        images: [
          'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=1200&auto=format&fit=crop&q=85',
          'https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?w=1200&auto=format&fit=crop&q=85',
          'https://images.unsplash.com/photo-1512374382149-233c42b6a83b?w=1200&auto=format&fit=crop&q=85',
          'https://images.unsplash.com/photo-1512374382149-233c42b6a83b?w=1200&auto=format&fit=crop&q=85',
        ],
      },
      {
        name: 'Obsidian Black',
        hex: '#111111',
        image: 'https://images.unsplash.com/photo-1556906781-9a412961c28c?w=1200&auto=format&fit=crop&q=85',
        images: [
          'https://images.unsplash.com/photo-1556906781-9a412961c28c?w=1200&auto=format&fit=crop&q=85',
          'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=1200&auto=format&fit=crop&q=85',
          'https://images.unsplash.com/photo-1512374382149-233c42b6a83b?w=1200&auto=format&fit=crop&q=85',
          'https://images.unsplash.com/photo-1512374382149-233c42b6a83b?w=1200&auto=format&fit=crop&q=85',
        ],
      },
      {
        name: 'Pure Chalk',
        hex: '#F8F9FA',
        image: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=1200&auto=format&fit=crop&q=85',
        images: [
          'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=1200&auto=format&fit=crop&q=85',
          'https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=1200&auto=format&fit=crop&q=85',
          'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=1200&auto=format&fit=crop&q=85',
          'https://images.unsplash.com/photo-1607522370275-f14206abe5d3?w=1200&auto=format&fit=crop&q=85',
        ],
      },
    ],
    sizes: [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 12],
    stock: 28,
    sku: 'SLV-RUN-001',
    rating: 4.9,
    reviewCount: 38,
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: true,
    specifications: {
      weight: '230g (Men US 9)',
      cushioning: 'AeroCell Supercritical Foam',
      drop: '8mm',
      upper: 'Engineered Recycled Mono-Mesh',
      midsole: 'Carbon Composite Torsion Plate',
      outsole: 'Vibram Megagrip Rubber',
    },
  },
  {
    name: 'Veloce Monaco Minimalist',
    slug: 'veloce-monaco-minimalist',
    brand: 'Veloce',
    category: 'Sneakers',
    gender: 'men',
    description: 'Subtle elegance meets street-smart craftsmanship. Handcrafted in Porto from full-grain calfskin leather with a cushioned Margom rubber cupsole. The waxed cotton laces and perforated leather lining provide climate control, forming the cornerstone of the modern luxury wardrobe.',
    shortDescription: 'Full-grain calfskin court sneaker with Italian Margom cupsole.',
    images: [
      'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1607522370275-f14206abe5d3?w=1200&auto=format&fit=crop&q=85',
    ],
    price: 19995,
    compareAtPrice: 22995,
    colors: [
      {
        name: 'Alabaster White',
        hex: '#FFFFFF',
        image: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=1200&auto=format&fit=crop&q=85',
        images: [
          'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=1200&auto=format&fit=crop&q=85',
          'https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=1200&auto=format&fit=crop&q=85',
          'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=1200&auto=format&fit=crop&q=85',
          'https://images.unsplash.com/photo-1607522370275-f14206abe5d3?w=1200&auto=format&fit=crop&q=85',
        ],
      },
      {
        name: 'Sandstone Grey',
        hex: '#D1D5DB',
        image: 'https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=1200&auto=format&fit=crop&q=85',
      },
      {
        name: 'Midnight Jet',
        hex: '#18181B',
        image: 'https://images.unsplash.com/photo-1556906781-9a412961c28c?w=1200&auto=format&fit=crop&q=85',
      },
    ],
    sizes: [8, 8.5, 9, 9.5, 10, 10.5, 11, 12],
    stock: 19,
    sku: 'VLC-SNK-002',
    rating: 4.8,
    reviewCount: 29,
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    specifications: {
      weight: '360g',
      cushioning: 'Memory-Ortholite Insole',
      drop: '4mm',
      upper: 'Italian Full-Grain Calfskin',
      midsole: 'Reinforced Rubber Cupsole',
      outsole: 'Margom Natural Gum',
    },
  },
  {
    name: 'Stratos Terra Hybrid Gore-X',
    slug: 'stratos-terra-hybrid-gore-x',
    brand: 'Stratos',
    category: 'Sports',
    gender: 'unisex',
    description: 'Engineered for seamless transitions between urban concrete and technical backcountry trails. Built with a weather-sealed waterproof membrane, speed-lacing cord, and multidirectional 5mm lugs that bite into rock and wet turf alike.',
    shortDescription: 'Weatherproof technical trail sneaker with quick-lace drawcord.',
    images: [
      'https://images.unsplash.com/photo-1582588678413-dbf45f4823e9?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1539185441755-769473a23570?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1520639888713-7851133b1ed0?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1544816155-12df9643f363?w=1200&auto=format&fit=crop&q=85',
    ],
    price: 16995,
    compareAtPrice: 19495,
    colors: [
      { name: 'Earth Slate', hex: '#4B5563' },
      { name: 'Forest Olive', hex: '#374151' },
      { name: 'Neon Citrus', hex: '#F59E0B' },
    ],
    sizes: [7, 8, 8.5, 9, 9.5, 10, 11, 12],
    stock: 14,
    sku: 'STR-TRL-003',
    rating: 4.9,
    reviewCount: 42,
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: false,
    specifications: {
      weight: '315g',
      cushioning: 'Dual-Chamber AirGel',
      drop: '10mm',
      upper: 'Ripstop Cordura with Weather Membrane',
      midsole: 'Reinforced EVA Rock Plate',
      outsole: '5mm Multidirectional Lug Rubber',
    },
  },
  {
    name: 'ApexLab HyperVelocity Carbon',
    slug: 'apexlab-hypervelocity-carbon',
    brand: 'ApexLab',
    category: 'Running',
    gender: 'unisex',
    description: 'The pinnacle of race-day speed. The HyperVelocity features a spoon-curved full-length carbon plate sandwiched between dual layers of PEBA foam. Calibrated for race paces under 4:00/km, giving you explosive bounce with every stride.',
    shortDescription: 'Full-length carbon fiber race shoe for record-breaking marathon speeds.',
    images: [
      '/products/apexlab/orange_profile.jpg',
      '/products/apexlab/orange_threequarter.jpg',
      '/products/apexlab/orange_sole.jpg',
      '/products/apexlab/orange_heel.jpg',
    ],
    price: 22495,
    compareAtPrice: 24995,
    colors: [
      {
        name: 'Hyper Orange',
        hex: '#FF5722',
        image: '/products/apexlab/orange_profile.jpg',
        images: [
          '/products/apexlab/orange_profile.jpg',
          '/products/apexlab/orange_threequarter.jpg',
          '/products/apexlab/orange_sole.jpg',
          '/products/apexlab/orange_heel.jpg',
        ],
      },
      {
        name: 'Ghost White',
        hex: '#FFFFFF',
        image: '/products/apexlab/white_profile.jpg',
        images: [
          '/products/apexlab/white_profile.jpg',
          '/products/apexlab/white_threequarter.jpg',
          '/products/apexlab/white_sole.jpg',
          '/products/apexlab/white_heel.jpg',
        ],
      },
    ],
    sizes: [7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11],
    stock: 11,
    sku: 'APX-CAR-004',
    rating: 5.0,
    reviewCount: 56,
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    specifications: {
      weight: '198g',
      cushioning: 'Nitro-PEBA Superfoam',
      drop: '6mm',
      upper: 'Ultra-thin VaporKnit Fabric',
      midsole: 'Spoon-Curved 3K Carbon Plate',
      outsole: 'Strategic Traction Pods',
    },
  },
  {
    name: 'SOLEVA Street Drift Low',
    slug: 'soleva-street-drift-low',
    brand: 'SOLEVA Core',
    category: 'Sneakers',
    gender: 'unisex',
    description: 'A modern classic redefined. Featuring a retro 90s tennis silhouette re-imagined with a deconstructed tongue, exposed foam collar, and chunky vintage off-white sole. Everyday swagger meets plush step-in comfort.',
    shortDescription: 'Retro-inspired street court sneaker with deconstructed details.',
    images: [
      'https://images.unsplash.com/photo-1600269452121-4f2416e55c28?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=1200&auto=format&fit=crop&q=85',
    ],
    price: 11495,
    compareAtPrice: 13495,
    colors: [
      { name: 'Chalk White / Vintage Green', hex: '#15803D' },
      { name: 'Monochrome Black', hex: '#18181B' },
    ],
    sizes: [6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 12],
    stock: 45,
    sku: 'SLV-DFT-005',
    rating: 4.7,
    reviewCount: 64,
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: true,
    specifications: {
      weight: '340g',
      cushioning: 'CloudFoot PU Footbed',
      drop: '0mm',
      upper: 'Action Leather with Suede Overlays',
      midsole: 'Textured Vintage Cupsole',
      outsole: 'Herringbone Tread Rubber',
    },
  },
  {
    name: 'AeroPulse SwiftStride Slip-On',
    slug: 'aeropulse-swiftstride-slip-on',
    brand: 'AeroPulse',
    category: 'Casual',
    gender: 'women',
    description: 'Designed for people on the move. Elastic seamless stretch-knit embraces the contours of your foot like a second skin. Step in effortlessly without untying laces, making it your go-to airport, commute, and weekend favorite.',
    shortDescription: 'Seamless stretch-knit slip-on sneaker with memory cushioning.',
    images: [
      '/products/aeropulse/swiftstride_profile.jpg',
      'https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1512374382149-233c42b6a83b?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1511556532299-8f662fc26c06?w=1200&auto=format&fit=crop&q=85',
    ],
    price: 8995,
    compareAtPrice: 10495,
    colors: [
      { name: 'Rose Quartz', hex: '#F472B6' },
      { name: 'Heather Grey', hex: '#9CA3AF' },
      { name: 'Onyx', hex: '#111827' },
    ],
    sizes: [6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10],
    stock: 32,
    sku: 'AER-SLP-006',
    rating: 4.6,
    reviewCount: 22,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    specifications: {
      weight: '210g',
      cushioning: 'CloudKnit Memory Cushion',
      drop: '6mm',
      upper: 'Elastic Circular 3D Knit',
      midsole: 'Flexible EVA Grooves',
      outsole: 'Anti-Slip Contact Zones',
    },
  },
  {
    name: 'ApexLab Gravity Court High-Top',
    slug: 'apexlab-gravity-court-high-top',
    brand: 'ApexLab',
    category: 'Basketball',
    gender: 'men',
    description: 'Command the hardwood and street alike. The Gravity Court delivers rigid lateral lockdown through an external TPU heel chassis, paired with a dual-stage responsive bounce unit in the forefoot for explosive pull-up jumpers.',
    shortDescription: 'High-performance basketball high-top with TPU chassis and dual bounce unit.',
    images: [
      'https://images.unsplash.com/photo-1552346154-21d32810aba3?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1515955656352-a1fa3ffcd111?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1512374382149-233c42b6a83b?w=1200&auto=format&fit=crop&q=85',
    ],
    price: 15995,
    compareAtPrice: 18495,
    colors: [
      { name: 'Neon Electric & Black', hex: '#10B981' },
      { name: 'Royal Ice Blue', hex: '#3B82F6' },
    ],
    sizes: [8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12, 13],
    stock: 18,
    sku: 'APX-BSK-007',
    rating: 4.9,
    reviewCount: 31,
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    specifications: {
      weight: '410g',
      cushioning: 'Dual AirPocket System',
      drop: '8mm',
      upper: 'Composite Armor Synthetic & Mesh',
      midsole: 'External Heel Ankle Cage',
      outsole: 'Radial Traction Hardwood Compound',
    },
  },
  {
    name: 'Veloce Riviera Suede Driver',
    slug: 'veloce-riviera-suede-driver',
    brand: 'Veloce',
    category: 'Lifestyle',
    gender: 'men',
    description: 'Tailored for weekend coastal escapes. Sourced from water-repellent Tuscan suede with hand-stitched moccasin toe detailing and pebble-rubber driving soles. Comfort meets understated refinement.',
    shortDescription: 'Water-repellent Tuscan suede driving moccasin with pebble sole.',
    images: [
      'https://images.unsplash.com/photo-1533867617858-e7b97e060509?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1614252369475-531eba835eb1?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=1200&auto=format&fit=crop&q=85',
    ],
    price: 17995,
    compareAtPrice: 20495,
    colors: [
      { name: 'Tobacco Camel', hex: '#B45309' },
      { name: 'Deep Navy', hex: '#1E3A8A' },
    ],
    sizes: [8, 8.5, 9, 9.5, 10, 11, 12],
    stock: 16,
    sku: 'VLC-DRV-008',
    rating: 4.8,
    reviewCount: 19,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    specifications: {
      weight: '290g',
      cushioning: 'Soft Calf Leather Padded Footbed',
      drop: '0mm',
      upper: 'Water-Repellent Tuscan Suede',
      midsole: 'Flexible Leather Midsole',
      outsole: 'Segmented Rubber Grip Pebbles',
    },
  },
  {
    name: 'SOLEVA Apex Phantom Triple Black',
    slug: 'soleva-apex-phantom-triple-black',
    brand: 'SOLEVA Core',
    category: 'Sneakers',
    gender: 'unisex',
    description: 'Total stealth, uncompromised performance. Murdered-out triple black styling constructed with ballistic nylon, matte nubuck overlays, and reflective 3M lace accents. Built to withstand nocturnal city excursions with dark luxury poise.',
    shortDescription: 'All-black tactical lifestyle sneaker with 3M reflective hits.',
    images: [
      'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1508609349937-5ec4ae374ebf?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1556906781-9a412961c28c?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1512374382149-233c42b6a83b?w=1200&auto=format&fit=crop&q=85',
    ],
    price: 14495,
    compareAtPrice: 16995,
    colors: [
      { name: 'Triple Black', hex: '#000000' },
    ],
    sizes: [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 12],
    stock: 35,
    sku: 'SLV-BLK-009',
    rating: 4.9,
    reviewCount: 47,
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    specifications: {
      weight: '330g',
      cushioning: 'AeroCell Dual Cushion',
      drop: '6mm',
      upper: 'Ballistic Nylon & Matte Nubuck',
      midsole: 'High-Density Jet Black Foam',
      outsole: 'Abrasion-Resistant Carbon Rubber',
    },
  },
  {
    name: 'AeroPulse CloudBurst Endurance',
    slug: 'aeropulse-cloudburst-endurance',
    brand: 'AeroPulse',
    category: 'Running',
    gender: 'women',
    description: 'Engineered for high-mileage half and full marathon conditioning. A plush 36mm heel stack height shields your joints from fatigue, while the breathable spacer mesh upper keeps internal temperatures balanced even on hot summer runs.',
    shortDescription: 'Max-cushion distance trainer engineered for fatigue resistance.',
    images: [
      '/products/aeropulse/cloudburst_profile.jpg',
      'https://images.unsplash.com/photo-1511556532299-8f662fc26c06?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1512374382149-233c42b6a83b?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1575537302964-96cd47c06b1b?w=1200&auto=format&fit=crop&q=85',
    ],
    price: 12995,
    compareAtPrice: 15495,
    colors: [
      { name: 'Lavender Mist', hex: '#A78BFA' },
      { name: 'Coral Flare', hex: '#FB7185' },
      { name: 'Glacier White', hex: '#FFFFFF' },
    ],
    sizes: [6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5],
    stock: 24,
    sku: 'AER-END-010',
    rating: 4.8,
    reviewCount: 36,
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: true,
    specifications: {
      weight: '240g',
      cushioning: 'CloudStack Max EVA',
      drop: '10mm',
      upper: 'Engineered Spacer Mesh',
      midsole: 'High-Stack Impact Absorption Core',
      outsole: 'DuraRubber High-Wear Heel Cap',
    },
  },
  {
    name: 'Stratos Alpine Trekker Mid',
    slug: 'stratos-alpine-trekker-mid',
    brand: 'Stratos',
    category: 'Sports',
    gender: 'men',
    description: 'Technical mid-top protection for rugged rocky scrambles. Built with waterproof eVent lining, protective rubber mudguard, and an ergonomic padded collar designed to prevent debris entry during rapid mountain ascents.',
    shortDescription: 'Waterproof mid-cut technical trekking shoe with rock plate.',
    images: [
      'https://images.unsplash.com/photo-1582588678413-dbf45f4823e9?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1539185441755-769473a23570?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1520639888713-7851133b1ed0?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1544816155-12df9643f363?w=1200&auto=format&fit=crop&q=85',
    ],
    price: 18995,
    compareAtPrice: 21495,
    colors: [
      { name: 'Granite Charcoal', hex: '#374151' },
      { name: 'Copper Tan', hex: '#9A3412' },
    ],
    sizes: [8, 8.5, 9, 9.5, 10, 10.5, 11, 12],
    stock: 15,
    sku: 'STR-TRK-011',
    rating: 4.7,
    reviewCount: 18,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    specifications: {
      weight: '440g',
      cushioning: 'Multi-Density Polyurethane',
      drop: '11mm',
      upper: 'Waterproof Split-Grain Leather & Cordura',
      midsole: 'Anatomic Steel Shank Protection',
      outsole: 'Deep Lug Vibram Trek Sole',
    },
  },
  {
    name: 'Veloce Firenze Chelsea Boot Sneaker',
    slug: 'veloce-firenze-chelsea-boot-sneaker',
    brand: 'Veloce',
    category: 'Lifestyle',
    gender: 'unisex',
    description: 'The iconic Chelsea silhouette fused with athletic trainer cushioning. Features supple Italian waxed pull-up leather, twin heavy-duty elastic side panels, and our signature vulcanized rubber sole. Dressed up or casual, it commands effortless style.',
    shortDescription: 'Hybrid Chelsea boot sneaker in Italian pull-up leather.',
    images: [
      '/products/veloce/chelsea_profile.jpg',
      'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1560343090-f0409e92791a?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1614252369475-531eba835eb1?w=1200&auto=format&fit=crop&q=85',
    ],
    price: 21995,
    compareAtPrice: 24995,
    colors: [
      { name: 'Cognac Amber', hex: '#92400E' },
      { name: 'Charcoal Black', hex: '#18181B' },
    ],
    sizes: [7, 8, 8.5, 9, 9.5, 10, 10.5, 11, 12],
    stock: 12,
    sku: 'VLC-CHL-012',
    rating: 4.9,
    reviewCount: 27,
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: false,
    specifications: {
      weight: '390g',
      cushioning: 'Orthopedic Leather Sockliner',
      drop: '4mm',
      upper: 'Waxed Pull-Up Calfskin',
      midsole: 'Vulcanized Flexible Rubber',
      outsole: 'Slip-Resistant Siped Gum',
    },
  },
  {
    name: 'SOLEVA AeroGlide Velocity 3',
    slug: 'soleva-aeroglide-velocity-3',
    brand: 'SOLEVA Core',
    category: 'Running',
    gender: 'men',
    description: 'Built for daily tempo intervals and swift recovery miles. Balanced cushioning keeps legs fresh mile after mile.',
    shortDescription: 'Dynamic daily tempo trainer with balanced shock attenuation.',
    images: [
      '/products/showcase/road_marathon.jpg',
      'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1512374382149-233c42b6a83b?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?w=1200&auto=format&fit=crop&q=85',
    ],
    price: 12495,
    compareAtPrice: 14495,
    colors: [
      { name: 'Solar Lime', hex: '#84CC16' },
      { name: 'Dark Gunmetal', hex: '#1F2937' },
    ],
    sizes: [7, 8, 8.5, 9, 9.5, 10, 10.5, 11],
    stock: 25,
    sku: 'SLV-GLD-013',
    rating: 4.6,
    reviewCount: 15,
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    specifications: { weight: '245g', drop: '8mm' },
  },
  {
    name: 'AeroPulse Studio Flow Trainer',
    slug: 'aeropulse-studio-flow-trainer',
    brand: 'AeroPulse',
    category: 'Sports',
    gender: 'women',
    description: 'Designed for pilates, HIIT classes, and gym workouts requiring agility and 360-degree pivoting.',
    shortDescription: 'Flexible studio training shoe with arch contour support.',
    images: [
      'https://images.unsplash.com/photo-1511556532299-8f662fc26c06?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1565814636199-ae8133055c1c?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1512374382149-233c42b6a83b?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1575537302964-96cd47c06b1b?w=1200&auto=format&fit=crop&q=85',
    ],
    price: 9995,
    compareAtPrice: 11995,
    colors: [
      { name: 'Blush Pearl', hex: '#FBCFE8' },
      { name: 'Cloud White', hex: '#FFFFFF' },
    ],
    sizes: [6, 6.5, 7, 7.5, 8, 8.5, 9],
    stock: 20,
    sku: 'AER-FLW-014',
    rating: 4.8,
    reviewCount: 24,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    specifications: { weight: '200g', drop: '4mm' },
  },
  {
    name: 'ApexLab Quantum Warp Tech',
    slug: 'apexlab-quantum-warp-tech',
    brand: 'ApexLab',
    category: 'Sneakers',
    gender: 'unisex',
    description: 'Avant-garde footwear design pushing structural envelopes with a geometric open-lattice 3D printed heel.',
    shortDescription: '3D printed parametric heel sneaker with futuristic tech aesthetic.',
    images: [
      'https://images.unsplash.com/photo-1562183241-b937e95585b6?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1520256862855-398228c41684?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1512374382149-233c42b6a83b?w=1200&auto=format&fit=crop&q=85',
    ],
    price: 23995,
    compareAtPrice: 27995,
    colors: [
      { name: 'Cyber Titanium', hex: '#94A3B8' },
      { name: 'Matrix Black', hex: '#0F172A' },
    ],
    sizes: [8, 8.5, 9, 9.5, 10, 11, 12],
    stock: 8,
    sku: 'APX-QNT-015',
    rating: 5.0,
    reviewCount: 19,
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: false,
    specifications: { weight: '370g', drop: '6mm' },
  },
  {
    name: 'Stratos Canyon Sandal Hybrid',
    slug: 'stratos-canyon-sandal-hybrid',
    brand: 'Stratos',
    category: 'Casual',
    gender: 'unisex',
    description: 'Breathable open-webbing hybrid shoe designed for summer river crossings and warm weather adventures.',
    shortDescription: 'Water-ready hybrid adventure sandal shoe with Vibram tread.',
    images: [
      'https://images.unsplash.com/photo-1603808033192-082d6919d3e1?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1595341888016-a392ef81b7de?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1582588678413-dbf45f4823e9?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1520639888713-7851133b1ed0?w=1200&auto=format&fit=crop&q=85',
    ],
    price: 9495,
    compareAtPrice: 10995,
    colors: [
      { name: 'Desert Dune', hex: '#D97706' },
      { name: 'Black Granite', hex: '#1F2937' },
    ],
    sizes: [7, 8, 9, 10, 11, 12],
    stock: 30,
    sku: 'STR-CYN-016',
    rating: 4.6,
    reviewCount: 16,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    specifications: { weight: '260g', drop: '0mm' },
  },
  {
    name: 'SOLEVA Urban Drift High',
    slug: 'soleva-urban-drift-high',
    brand: 'SOLEVA Core',
    category: 'Sneakers',
    gender: 'men',
    description: 'High-top attitude with premium calf suede and perforated collar cushioning for maximum street presence.',
    shortDescription: 'Premium high-top skate and street sneaker with padded collar.',
    images: [
      'https://images.unsplash.com/photo-1597045566677-8cf032ed6634?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1516478177764-9fe5bd7e9717?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1552346154-21d32810aba3?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=1200&auto=format&fit=crop&q=85',
    ],
    price: 13495,
    compareAtPrice: 15995,
    colors: [
      { name: 'Chalk & Crimson', hex: '#EF4444' },
      { name: 'Midnight Shadow', hex: '#111827' },
    ],
    sizes: [8, 8.5, 9, 9.5, 10, 10.5, 11, 12],
    stock: 22,
    sku: 'SLV-UDH-017',
    rating: 4.8,
    reviewCount: 39,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    specifications: { weight: '390g', drop: '4mm' },
  },
  {
    name: 'Veloce Roma Perforated Derby',
    slug: 'veloce-roma-perforated-derby',
    brand: 'Veloce',
    category: 'Lifestyle',
    gender: 'men',
    description: 'Brogue detailing reimagined with a lightweight EVA sport sole for office-to-dinner effortless sophistication.',
    shortDescription: 'Hybrid dress derby shoe with ultra-soft sport sole.',
    images: [
      'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1617606002779-51d866bdd1d1?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1533867617858-e7b97e060509?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=1200&auto=format&fit=crop&q=85',
    ],
    price: 18995,
    compareAtPrice: 21995,
    colors: [
      { name: 'Espresso Brown', hex: '#78350F' },
      { name: 'Onyx Black', hex: '#000000' },
    ],
    sizes: [8, 8.5, 9, 9.5, 10, 11, 12],
    stock: 14,
    sku: 'VLC-RMA-018',
    rating: 4.7,
    reviewCount: 14,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    specifications: { weight: '340g', drop: '8mm' },
  },
  {
    name: 'AeroPulse FreeSpirit Flex Knit',
    slug: 'aeropulse-freespirit-flex-knit',
    brand: 'AeroPulse',
    category: 'Casual',
    gender: 'women',
    description: 'Barefoot-inspired freedom with just enough cushion to keep city sidewalks comfortable all day.',
    shortDescription: 'Ultra-flexible knit sneaker with anatomical toe box.',
    images: [
      '/products/aeropulse/freespirit_profile.jpg',
      'https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1512374382149-233c42b6a83b?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1575537302964-96cd47c06b1b?w=1200&auto=format&fit=crop&q=85',
    ],
    price: 10495,
    compareAtPrice: 12495,
    colors: [
      { name: 'Oatmeal Heather', hex: '#E5E7EB' },
      { name: 'Sage Green', hex: '#059669' },
    ],
    sizes: [6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5],
    stock: 27,
    sku: 'AER-FSP-019',
    rating: 4.7,
    reviewCount: 28,
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    specifications: { weight: '190g', drop: '2mm' },
  },
  {
    name: 'ApexLab AeroShield Cross-Trainer',
    slug: 'apexlab-aeroshield-cross-trainer',
    brand: 'ApexLab',
    category: 'Sports',
    gender: 'unisex',
    description: 'Heavy lifting meets sprint conditioning. Wide flat base with TPU heel cup prevents collapse under barbell loads.',
    shortDescription: 'Stable flat-base training shoe for weightlifting and functional fitness.',
    images: [
      'https://images.unsplash.com/photo-1579338559194-a162d19bf842?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1518002171953-a080ee817e1f?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1512374382149-233c42b6a83b?w=1200&auto=format&fit=crop&q=85',
    ],
    price: 13995,
    compareAtPrice: 15995,
    colors: [
      { name: 'Concrete Grey & Solar Orange', hex: '#EA580C' },
      { name: 'Pitch Black', hex: '#111827' },
    ],
    sizes: [7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 12],
    stock: 19,
    sku: 'APX-CRS-020',
    rating: 4.8,
    reviewCount: 33,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    specifications: { weight: '320g', drop: '4mm' },
  },
  {
    name: 'SOLEVA SkyHop Junior Spark',
    slug: 'soleva-skyhop-junior-spark',
    brand: 'SOLEVA Core',
    category: 'Sneakers',
    gender: 'kids',
    description: 'Designed for tireless playground energy. Reinforced scuff-proof toe cap and non-marking grippy rubber sole.',
    shortDescription: 'Durable and bouncy kids performance sneaker with easy strap.',
    images: [
      'https://images.unsplash.com/photo-1514989940723-e8e51635b782?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1556906781-9a412961c28c?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1512374382149-233c42b6a83b?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1575537302964-96cd47c06b1b?w=1200&auto=format&fit=crop&q=85',
    ],
    price: 6995,
    compareAtPrice: 7995,
    colors: [
      { name: 'Electric Cobalt', hex: '#2563EB' },
      { name: 'Neon Sun', hex: '#FACC15' },
    ],
    sizes: [3, 3.5, 4, 4.5, 5, 5.5, 6],
    stock: 24,
    sku: 'SLV-KID-021',
    rating: 4.9,
    reviewCount: 20,
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    specifications: { weight: '180g', drop: '4mm' },
  },
  {
    name: 'Stratos StormChaser Winter Boot',
    slug: 'stratos-stormchaser-winter-boot',
    brand: 'Stratos',
    category: 'Sports',
    gender: 'unisex',
    description: 'Thermal insulated cold-weather footwear rated down to -20°C. Hydrophobic outer shell with Thinsulate lining.',
    shortDescription: 'Sub-zero insulated winter sneaker boot with Arctic ice grip.',
    images: [
      '/products/stratos/stormchaser_profile.jpg',
      'https://images.unsplash.com/photo-1542838132-92c53300491e?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1520639888713-7851133b1ed0?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1544816155-12df9643f363?w=1200&auto=format&fit=crop&q=85',
    ],
    price: 20495,
    compareAtPrice: 23495,
    colors: [
      { name: 'Polar White', hex: '#FFFFFF' },
      { name: 'Tarmac Grey', hex: '#4B5563' },
    ],
    sizes: [8, 8.5, 9, 9.5, 10, 11, 12],
    stock: 10,
    sku: 'STR-WNT-022',
    rating: 4.8,
    reviewCount: 17,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    specifications: { weight: '480g', drop: '8mm' },
  },
  {
    name: 'Veloce Venezia Knit Loafer',
    slug: 'veloce-venezia-knit-loafer',
    brand: 'Veloce',
    category: 'Lifestyle',
    gender: 'men',
    description: 'Modern Italian penny loafer reimagined with breathable high-gauge merino wool knit and leather welt.',
    shortDescription: 'Merino knit penny loafer hybrid with hand-burnished leather trim.',
    images: [
      'https://images.unsplash.com/photo-1560343090-f0409e92791a?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1533867617858-e7b97e060509?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=1200&auto=format&fit=crop&q=85',
    ],
    price: 17495,
    compareAtPrice: 19995,
    colors: [
      { name: 'Heather Charcoal', hex: '#374151' },
      { name: 'Sand Khaki', hex: '#D97706' },
    ],
    sizes: [8, 8.5, 9, 9.5, 10, 10.5, 11, 12],
    stock: 17,
    sku: 'VLC-VNZ-023',
    rating: 4.7,
    reviewCount: 11,
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    specifications: { weight: '295g', drop: '4mm' },
  },
  {
    name: 'ApexLab Orbit Fly Low-Drop',
    slug: 'apexlab-orbit-fly-low-drop',
    brand: 'ApexLab',
    category: 'Running',
    gender: 'unisex',
    description: 'Zero-drop natural stride footwear with low-profile responsive foam for runners who prefer maximum ground feedback.',
    shortDescription: 'Natural zero-drop lightweight racer with tactile road feel.',
    images: [
      'https://images.unsplash.com/photo-1538805060514-97d9cc17730c?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1463100099107-aa0980c362e6?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1512374382149-233c42b6a83b?w=1200&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1512374382149-233c42b6a83b?w=1200&auto=format&fit=crop&q=85',
    ],
    price: 13495,
    compareAtPrice: 15495,
    colors: [
      { name: 'Solar Orange & White', hex: '#F97316' },
      { name: 'Graphite Night', hex: '#1E293B' },
    ],
    sizes: [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11],
    stock: 21,
    sku: 'APX-ORB-024',
    rating: 4.8,
    reviewCount: 26,
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    specifications: { weight: '215g', drop: '0mm' },
  },
];

const sampleReviews = [
  {
    rating: 5,
    title: 'The best footwear investment this year',
    comment: 'The cushioning and attention to detail are on another level. I get compliments everywhere I wear these. Fits true to size and arrived in immaculate packaging.',
    verifiedPurchase: true,
  },
  {
    rating: 5,
    title: 'Unbelievable energy return',
    comment: 'I shaved 45 seconds off my 5K pace on my very first run. The lock-in is firm and zero hot spots or blisters even after 15 miles.',
    verifiedPurchase: true,
  },
  {
    rating: 4,
    title: 'Superb quality and minimalist aesthetic',
    comment: 'Leather quality is magnificent. A tiny bit snug on the width for the first two days, then broke in like a glove. Highly recommended.',
    verifiedPurchase: true,
  },
  {
    rating: 5,
    title: 'Worth every single penny',
    comment: 'Clean lines, featherlight on foot, and the foam stays responsive even in cold mornings. SOLEVA has made a lifelong customer.',
    verifiedPurchase: true,
  },
];

const couponsData = [
  {
    code: 'WELCOME10',
    discountType: 'percentage',
    discountValue: 10,
    minOrderValue: 4999,
    maxDiscount: 2000,
    expiresAt: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    code: 'SOLEVA20',
    discountType: 'percentage',
    discountValue: 20,
    minOrderValue: 9999,
    maxDiscount: 4000,
    expiresAt: new Date(Date.now() + 180 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    code: 'FLASH50',
    discountType: 'fixed',
    discountValue: 1500,
    minOrderValue: 14999,
    expiresAt: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
];

export const seedDatabase = async () => {
  try {
    console.log('--- Seeding SOLEVA Database ---');
    await connectDB();

    // Clear existing collections
    console.log('Clearing existing data collections...');
    await Promise.all([
      User.deleteMany({}),
      Category.deleteMany({}),
      Brand.deleteMany({}),
      Product.deleteMany({}),
      Review.deleteMany({}),
      Coupon.deleteMany({}),
      Order.deleteMany({}),
    ]);

    // 1. Create Admin & Demo Customer
    console.log('Creating Admin and Customer accounts...');
    const adminEmail = process.env.ADMIN_EMAIL || 'admin@soleva.com';
    const adminPassword = process.env.ADMIN_PASSWORD || 'Admin@123456';

    const adminUser = await User.create({
      name: 'SOLEVA Flagship Admin',
      email: adminEmail,
      password: adminPassword,
      phone: '+91 1800 209 8888',
      role: 'admin',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
      addresses: [
        {
          fullName: 'SOLEVA India Flagship',
          phone: '+91 1800 209 8888',
          street: 'UB City, Level 14, Concorde Block, Vittal Mallya Road',
          apartment: 'Suite 1402',
          city: 'Bengaluru',
          state: 'Karnataka',
          pincode: '560001',
          country: 'India',
          isDefault: true,
        },
      ],
    });

    const demoCustomer = await User.create({
      name: 'Aarav Sharma',
      email: 'customer@example.com',
      password: 'Customer@123',
      phone: '+91 98765 43210',
      role: 'customer',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
      addresses: [
        {
          fullName: 'Aarav Sharma',
          phone: '+91 98765 43210',
          street: 'Flat 402, Sea Green Apartments, Linking Road',
          apartment: 'Near Mehboob Studio, Bandra West',
          city: 'Mumbai',
          state: 'Maharashtra',
          pincode: '400050',
          country: 'India',
          isDefault: true,
        },
      ],
    });

    console.log(`Admin created: ${adminUser.email}`);
    console.log(`Customer created: ${demoCustomer.email}`);

    // 2. Insert Categories & Brands
    console.log('Inserting Categories and Brands...');
    await Category.insertMany(categoriesData);
    await Brand.insertMany(brandsData);

    // 3. Insert Coupons
    console.log('Inserting promotional coupons...');
    await Coupon.insertMany(couponsData);

    // 4. Insert Products
    console.log('Inserting 24 luxury footwear products...');
    const insertedProducts = await Product.insertMany(productsData);

    // 5. Insert Sample Reviews for first few products
    console.log('Generating verified customer reviews...');
    for (let i = 0; i < Math.min(8, insertedProducts.length); i++) {
      const prod = insertedProducts[i];
      const reviewTemplate = sampleReviews[i % sampleReviews.length];

      await Review.create({
        product: prod._id,
        user: demoCustomer._id,
        userName: demoCustomer.name,
        userAvatar: demoCustomer.avatar,
        rating: reviewTemplate.rating,
        title: reviewTemplate.title,
        comment: reviewTemplate.comment,
        verifiedPurchase: true,
      });
    }

    // 6. Create sample orders for admin dashboard demonstration
    console.log('Creating initial realistic orders for analytics...');
    const p1 = insertedProducts[0];
    const p2 = insertedProducts[1];

    await Order.create({
      orderNumber: 'SLV-IND-2026-9041',
      user: demoCustomer._id,
      items: [
        {
          product: p1._id,
          name: p1.name,
          image: p1.images[0],
          size: 9,
          color: p1.colors[0].name,
          quantity: 1,
          price: p1.price,
          total: p1.price,
        },
        {
          product: p2._id,
          name: p2.name,
          image: p2.images[0],
          size: 10,
          color: p2.colors[0].name,
          quantity: 1,
          price: p2.price,
          total: p2.price,
        },
      ],
      shippingAddress: {
        fullName: demoCustomer.addresses[0].fullName,
        phone: demoCustomer.addresses[0].phone,
        email: demoCustomer.email,
        address: demoCustomer.addresses[0].street,
        apartment: demoCustomer.addresses[0].apartment,
        city: demoCustomer.addresses[0].city,
        state: demoCustomer.addresses[0].state,
        pincode: demoCustomer.addresses[0].pincode,
        country: demoCustomer.addresses[0].country,
      },
      deliveryOption: {
        id: 'express',
        title: 'Blue Dart Priority Air Express',
        price: 750,
        estimatedDays: '1-2 Business Days',
      },
      paymentMethod: 'UPI / Net Banking',
      paymentStatus: 'paid',
      orderStatus: 'Delivered',
      subtotal: p1.price + p2.price,
      discount: 0,
      shippingFee: 750,
      tax: Math.round((p1.price + p2.price) * 0.18),
      totalAmount: Math.round((p1.price + p2.price) * 1.18 + 750),
      trackingNumber: 'BLUEDART-9281740192',
      timeline: [
        { status: 'Confirmed', note: 'Payment verified via UPI', timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000) },
        { status: 'Processing', note: 'Order packed in Bengaluru fulfillment hub', timestamp: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000) },
        { status: 'Shipped', note: 'Dispatched via Blue Dart Air Express', timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000) },
        { status: 'Delivered', note: 'Package handed directly to resident with OTP verification', timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000) },
      ],
    });

    console.log('✅ SOLEVA Database Seeding Completed Successfully!');
  } catch (err: any) {
    console.error('❌ Database seeding failed:', err);
    throw err;
  }
};

// Run directly if script called from CLI
if (require.main === module) {
  seedDatabase()
    .then(async () => {
      await disconnectDB();
      process.exit(0);
    })
    .catch((err) => {
      console.error(err);
      process.exit(1);
    });
}
